version: '3.8'
services:
  app:
    image: 'goharbor/harbor-core:latest'
    container_name: panel-harbor
    restart: unless-stopped
    labels:
      managed-by: "opsv-kits-store"
    ports:
      - '${HARBOR_PORT}:80'
    volumes:
      - /www/server/apps/harbor/data:/data
    environment:
      HARBOR_ADMIN_PASSWORD: '${HARBOR_ADMIN_PASSWORD}'
