version: '3.8'
services:
  app:
    image: 'lissy93/dashy:latest'
    container_name: panel-dashy
    restart: unless-stopped
    labels:
      managed-by: "opsv-kits-store"
    ports:
      - '${DASHY_PORT}:8080'
    volumes:
      - /www/server/apps/dashy/data:/app/public/conf.yml
