version: '3.8'
services:
  app:
    image: 'discourse/discourse:latest'
    container_name: panel-discourse
    restart: unless-stopped
    labels:
      managed-by: "opsv-kits-store"
    ports:
      - '${DISCOURSE_PORT}:3000'
    volumes:
      - /www/server/apps/discourse/data:/shared
    environment:
      DISCOURSE_HOSTNAME: '${DISCOURSE_HOSTNAME}'
