version: '3.8'
services:
  app:
    image: 'jenkins/jenkins:lts'
    container_name: panel-jenkins
    restart: unless-stopped
    labels:
      managed-by: "opsv-kits-store"
    ports:
      - '${JENKINS_PORT}:8080'
    volumes:
      - /www/server/apps/jenkins/data:/var/jenkins_home
