version: '3.8'
services:
  app:
    image: 'emby/embyserver:latest'
    container_name: panel-emby
    restart: unless-stopped
    labels:
      managed-by: "opsv-kits-store"
    ports:
      - '${EMBY_PORT}:8096'
    volumes:
      - /www/server/apps/emby/data:/config
