version: '3.8'
services:
  app:
    image: 'penpotapp/frontend:latest'
    container_name: panel-penpot
    restart: unless-stopped
    labels:
      managed-by: "opsv-kits-store"
    ports:
      - '${PENPOT_PORT}:80'
    volumes:
      - /www/server/apps/penpot/data:/opt/data
