version: '3.8'
services:
  app:
    image: 'corentinth/it-tools:latest'
    container_name: panel-it-tools
    restart: unless-stopped
    labels:
      managed-by: "opsv-kits-store"
    ports:
      - '${ITTOOLS_PORT}:80'
