version: '3.8'
services:
  app:
    image: 'httpd:alpine'
    container_name: panel-apache
    restart: unless-stopped
    labels:
      managed-by: "opsv-kits-store"
    ports:
      - '${APACHE_PORT}:80'
    volumes:
      - /www/server/apps/apache/data:/usr/local/apache2/htdocs
      - /www/server/apps/apache/conf:/usr/local/apache2/conf
