version: '3.8'
services:
  app:
    image: 'containous/whoami:latest'
    container_name: panel-whoami
    restart: unless-stopped
    labels:
      managed-by: "opsv-kits-store"
    ports:
      - '${WHOAMI_PORT}:80'
