version: '3.8'
services:
  app:
    image: 'amir20/dozzle:latest'
    container_name: panel-dozzle
    restart: unless-stopped
    labels:
      managed-by: "opsv-kits-store"
    ports:
      - '${DOZZLE_PORT}:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
