version: '3.8'
services:
  app:
    image: 'elasticsearch:8.15.0'
    container_name: panel-elasticsearch
    restart: unless-stopped
    labels:
      managed-by: "opsv-kits-store"
    ports:
      - '${ES_HTTP_PORT}:9200'
      - '${ES_TRANSPORT_PORT}:9300'
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      xpack.security.enabled: 'false'
    volumes:
      - /www/server/apps/elasticsearch/data:/usr/share/elasticsearch/data
