version: '3.8'
services:
  app:
    image: 'excalidraw/excalidraw:latest'
    container_name: panel-excalidraw
    restart: unless-stopped
    labels:
      managed-by: "opsv-kits-store"
    ports:
      - '${EXCALIDRAW_PORT}:80'
